server:
port: 8080

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/daily_food_consumption?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: daily-food-admin
    password: admin
